name: Release
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      semanticReleaseOptions:
        description: semantic-release cli options
        required: false
        default: ""
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.4.1
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.4.0"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm prepack
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm semantic-release ${{ inputs.semanticReleaseOptions }}
